// ============================================================================================= //
/**
* [ global.adp.endpoints.microservice.update ]
* Update a <b>Microservice</b> register, if the JSON object is conform the <b>Schema</b> and
* the <b>Token</b> belongs to an <b>Administrator</b> or one of the <b>Onwers of the
* MicroService</b>.
* @param {String} Inline Just put the address of this endPoint.
* @param {String} Authorization as string on the header of the request.
* @param {raw} Body Add a JSON on the Raw Body of the Post request. The <b>Content</b>
* of this JSON should be a valid <b>MicroService</b>.
* @author Armando Schiavon Dias [escharm]
*/
// ============================================================================================= //
/**
 * @swagger
 * /microservice/{ID}:
 *    put:
 *      description: Updates a <b>Microservice</b> details, for the given microservice ID
 *                   and fields to change given in JSON object. Given JSON object should match
 *                   the <b>Schema</b> and the <b>Token</b> should belong either to a
 *                   <b>Administrator</b> or <b>Onwers</b>. ID can be given in URL "inline path" or
 *                   in JSON object as _id. Incase if ID is mentioned in URL path and JSON object,
 *                   Make sure to specify exact same ID in both place to avoid Bad request.
 *      summary: Update microservice details, ID is optional
 *      requestBody:
 *          description: "Add JSON object in Raw Body of the Post request.
 *                       The <b>Content</b> of this JSON should be a valid <b>Schema</b>."
 *          required: true
 *          content:
 *            application/json:
 *              schema:
 *                type: object
 *                properties:
 *                  _id:
 *                    type: string
 *                    example: Microservice ID
 *                  name:
 *                    type: string
 *                    example: Microservice Name
 *      responses:
 *        '201':
 *          $ref: '#/components/responses/Ok'
 *        '401':
 *          $ref: '#/components/responses/Unauthorized'
 *        '403':
 *          $ref: '#/components/responses/Forbidden'
 *        '500':
 *          $ref: '#/components/responses/InternalServerError'
 *      tags:
 *        - Microservice
 *      parameters:
 *      - name: ID
 *        in: path
 *        description: Enter Microservice ID
 *        schema:
 *          type: string
 *          format: string
 */
// ============================================================================================= //
global.adp.docs.rest.push(__filename);
// ============================================================================================= //
const errorLog = require('./../../../library/errorLog');
// ============================================================================================= //
module.exports = (REQ, RES) => {
  const packname = 'global.adp.endpoints.microservice.update';
  const timer = new Date();
  const newMicroService = REQ.body;
  const myMSfromURL = REQ.params.id;
  /* eslint-disable no-underscore-dangle */
  /* _id is generated by CouchDB. We cannot change it! */
  const myMSfromBody = newMicroService._id;
  /* eslint-disable no-underscore-dangle */
  const fromURL = !((myMSfromURL === null) || (myMSfromURL === undefined) || (myMSfromURL === ''));
  const fromBody = !((myMSfromBody === null) || (myMSfromBody === undefined) || (myMSfromBody === ''));
  let myMS = null;
  if (fromURL && fromBody) {
    if (myMSfromURL !== myMSfromBody) {
      return global.adp.Answers.answerWith(400, RES, timer, 'Two different _id variables. Send just one.');
    }
    myMS = myMSfromBody;
  }
  if (fromURL && !fromBody) {
    myMS = myMSfromURL;
  }
  if (!fromURL && fromBody) {
    myMS = myMSfromBody;
  }
  if (myMS === null) {
    return global.adp.Answers.answerWith(400, RES, timer, 'Id not received.');
  }
  return global.adp.permission.canDoIt(REQ, myMS)
    .then(() => {
      const user = REQ.user.docs[0];
      const userOBJ = {
        signum: user.signum.trim().toLowerCase(),
        role: user.role,
      };
      return global.adp.microservice.update(myMS, newMicroService, userOBJ)
        .then((RETURNOBJ) => {
          const msg = `Microservice updated in ${(new Date()).getTime() - timer.getTime()}ms`;
          const obj = { microserviceId: myMS, user: userOBJ };
          adp.echoLog(msg, obj, 200, packname);
          return global.adp.Answers.answerWith(200, RES, timer, 'Update Successful!', RETURNOBJ);
        })
        .catch((finalResult) => {
          let errorText;
          let errorOBJ;
          switch (finalResult) {
            case 404:
              errorText = 'Error on [ adp.microservice.update ]: Microservice not found';
              errorOBJ = {
                microserviceId: myMS,
                user: userOBJ,
                error: finalResult,
                newMicroServiceToUpdate: newMicroService,
              };
              errorLog(404, errorText, errorOBJ, 'mainFunction', packname, true);
              return global.adp.Answers.answerWith(404, RES, timer);
            case 500:
              errorText = 'Error on [ adp.microservice.update ]';
              errorOBJ = {
                microserviceId: myMS,
                error: finalResult,
                user: userOBJ,
                newMicroServiceToUpdate: newMicroService,
              };
              errorLog(500, errorText, errorOBJ, 'mainFunction', packname, true);
              return global.adp.Answers.answerWith(500, RES, timer);
            default:
              errorText = 'Error on [ adp.microservice.update ]: Bad Request';
              errorOBJ = {
                microserviceId: myMS,
                error: finalResult,
                user: userOBJ,
                newMicroServiceToUpdate: newMicroService,
              };
              errorLog(400, errorText, errorOBJ, 'mainFunction', packname, true);
              return global.adp.Answers.answerWith(400, RES, timer, null, finalResult);
          }
        });
    })
    .catch((error) => {
      const errorText = 'Error on [ adp.permission.canDoIt ]';
      const errorOBJ = { microserviceId: myMS, header: REQ.headers };
      adp.echoLog(errorText, errorOBJ, 403, packname, true);
      global.adp.Answers.answerWith(403, RES, timer, error);
    });
};
// ============================================================================================= //
