#%RAML 1.0
title: Portal Update
version: v1
baseUri: https://adp.ericsson.se/api/integration/{version}/
mediaType: [ application/json ]
types:
  RefreshFeedback:
    description: |
             Indicates a service that has been refreshed by this call.
    properties:
      id: string
      name: string
      errors:
        description: |
          Errors that occurred during the refresh.
          Errors will block the refresh and the HTTP Status Code will be 400 (Bad Request).
        properties:
          development: string[]
          release: string[]
      quant_errors: number
      warnings:
        description: |
          Warnings that occurred during the refresh.
          Warnings will not block the refresh.
          Only Warnings with zero errors will keep the HTTP Status Code as 200 (Ok).
        properties:
          development: string[]
          release: string[]
      quant_warnings: number

securitySchemes:
  jwt:
    description: |
      The JWT token generated in the ADP portal for each service is used to authenticate calls to this api.
    type: x-jwt
    describedBy:
      headers:
        Authorization:
          description: |
             Used to send a valid JWT access token. Do not use
             with the "access_token" query string parameter.
          type: string
      queryParameters:
        access_token:
          description: |
             Used to send a valid JWT access token. Do not use with
             the "Authorization" header.
          type: string
      responses:
        401:
          description: |
              Bad or expired token. This can happen if the user or Portal
              revoked or expired an access token. To fix, re-authenticate
              the user.
/microservice/documentrefresh:
  description: |
    Notify the portal that your release documentation has been updated and
    should be refreshed.
  post:
    securedBy:
      jwt  
    body:
      application/json:
    responses:
      200:
      400:
        body: 
          application/json:
            RefreshFeedback[]