// ============================================================================================= //
module.exports = () => {
// --------------------------------------------------------------------------------------------- //
  const complianceOptions = [
    {
      _id: '36faa3f38deab95a43191578450087d9',
      type: 'group',
      name: 'Non Functional',
      desc: '',
      'group-id': 1,
      'test-id': 'compliance-group-non-functional',
      order: 1,
      slug: 'non-functional',
    },
    {
      _id: '36faa3f38deab95a431915784500a2f0',
      type: 'group',
      name: 'Integration',
      desc: '',
      'group-id': 2,
      'test-id': 'compliance-group-integration',
      order: 2,
      slug: 'integration',
    },
    {
      _id: '36faa3f38deab95a431915784500b202',
      'field-id': 1,
      type: 'field',
      name: 'Manual scalable',
      desc: 'This service supports manually triggered scaling',
      'group-id': 1,
      'test-id': 'compliance-field-manual-scalable',
      order: 1,
      slug: 'manual-scalable',
    },
    {
      _id: '36faa3f38deab95a431915784500d153',
      'field-id': 2,
      type: 'field',
      name: 'Automatic scalable',
      desc: 'This service supports automatic scaling',
      'group-id': 1,
      'test-id': 'compliance-field-automatic-scalable',
      order: 2,
      slug: 'automatic-scalable',
    },
    {
      _id: '36faa3f38deab95a431915784500ea8f',
      'field-id': 3,
      type: 'field',
      name: 'High Availability',
      desc: 'This service supports High Availability since it supports multiple replicas',
      'group-id': 1,
      'test-id': 'compliance-field-high-availability',
      order: 3,
      slug: 'high-availability',
    },
    {
      _id: '36faa3f38deab95a4319157845010927',
      'field-id': 4,
      type: 'field',
      name: 'Single Availability',
      desc: 'This service supports Single Availability since it supports one single replica',
      'group-id': 1,
      'test-id': 'compliance-field-single-availability',
      order: 4,
      slug: 'single-availability',
    },
    {
      _id: '36faa3f38deab95a4319157845011527',
      'field-id': 5,
      type: 'field',
      name: 'Stateless',
      desc: 'This service is stateless, it does not maintain a state',
      'group-id': 1,
      'test-id': 'compliance-field-stateless',
      order: 5,
      slug: 'stateless',
    },
    {
      _id: '36faa3f38deab95a4319157845012de9',
      'field-id': 1,
      type: 'field',
      name: 'CM',
      desc: 'This service provides CM capabilities. It has been integrated with the CM Functional Area',
      'group-id': 2,
      'test-id': 'compliance-field-cm',
      order: 1,
      slug: 'cm',
    },
    {
      _id: '36faa3f38deab95a431915784501451b',
      'field-id': 2,
      type: 'field',
      name: 'Logging',
      desc: 'This service supports Logging according to the ADP Logging Functional Area',
      'group-id': 2,
      'test-id': 'compliance-field-logging',
      order: 2,
      slug: 'logging',
    },
    {
      _id: '36faa3f38deab95a431915784501511c',
      'field-id': 3,
      type: 'field',
      name: 'PM',
      desc: 'This service supports Performance Management (PM) according to the ADP PM Functional Area',
      'group-id': 2,
      'test-id': 'compliance-field-pm',
      order: 3,
      slug: 'pm',
    },
    {
      _id: '36faa3f38deab95a4319157845016814',
      'field-id': 4,
      type: 'field',
      name: 'Distributed Trace',
      desc: 'This service provides tracing capabilities according to the ADP Distributed Trace Functional Area',
      'group-id': 2,
      'test-id': 'compliance-field-distributed-trace',
      order: 4,
      slug: 'distributed-trace',
    },
    {
      _id: '36faa3f38deab95a4319157845017410',
      'field-id': 5,
      type: 'field',
      name: 'Key Management',
      desc: 'This service is integrated with the Security Features provided through Key Management Functional Area',
      'group-id': 2,
      'test-id': 'compliance-field-key-management',
      order: 5,
      slug: 'key-management',
    },
    {
      _id: '36faa3f38deab95a4319157845018642',
      'field-id': 6,
      type: 'field',
      name: 'Identity Management',
      desc: 'This service is integrated with the authentication and authorization features provided through Identity Management Functional Area',
      'group-id': 2,
      'test-id': 'compliance-field-identity-management',
      order: 6,
      slug: 'identity-management',
    },
    {
      _id: '36faa3f38deab95a4319157845019a96',
      'field-id': 7,
      type: 'field',
      name: 'Internal Security (SIP-TLS)',
      desc: 'This service is integrated with SIP-TLS for cluster internal service to service communication',
      'group-id': 2,
      'test-id': 'compliance-field-internal-security-sip-tls',
      order: 7,
      slug: 'internal-security-sip-tls',
    },
    {
      _id: '36faa3f38deab95a431915784501ae8d',
      'field-id': 8,
      type: 'field',
      name: 'Backup & Restore',
      desc: 'This service supports backup and restore of data according to the ADP Backup & Restore Functional area',
      'group-id': 2,
      'test-id': 'compliance-field-backup-and-restore',
      order: 8,
      slug: 'backup-and-restore',
    },
    {
      _id: '36faa3f38deab95a431915784501bf9f',
      'field-id': 9,
      type: 'field',
      name: 'Internal Security (Service Mesh)',
      desc: 'This service is integrated with Service Mesh',
      'group-id': 2,
      'test-id': 'compliance-field-internal-security-service-mesh',
      order: 9,
      slug: 'internal-security-service-mesh',
    },
    {
      _id: '36faa3f38deab95a431915784501c838',
      'field-id': 10,
      type: 'field',
      name: 'Certificate Management',
      desc: 'This service is integrated with Certificate Management for secure external communication',
      'group-id': 2,
      'test-id': 'compliance-field-certificate-management',
      order: 10,
      slug: 'certificate-management',
    },
    {
      _id: '36faa3f38deab95a431915784501d34c',
      'field-id': 11,
      type: 'field',
      name: 'Fault Management',
      desc: 'This service is integrated with the ADP Fault Management Functional Area',
      'group-id': 2,
      'test-id': 'compliance-field-fault-management',
      order: 11,
      slug: 'fault-management',
    },
    {
      _id: '36faa3f38deab95a431915784501f13b',
      'field-id': 12,
      type: 'field',
      name: 'License Management',
      desc: 'This service provides licensing capabilities according to the ADP License Management Functional Area',
      'group-id': 2,
      'test-id': 'compliance-field-license-management',
      order: 12,
      slug: 'license-management',
    },
    {
      _id: '36faa3f38deab95a43191578450201a9',
      'select-id': 0,
      type: 'answer',
      name: 'Awaiting Input',
      desc: '',
      'test-id': 'compliance-answer-awaiting-input',
      order: 1,
      slug: 'awaiting-input',
      default: true,
    },
    {
      _id: '36faa3f38deab95a43191578450217c5',
      'select-id': 1,
      type: 'answer',
      name: 'Yes',
      desc: '',
      'test-id': 'compliance-answer-yes',
      order: 2,
      slug: 'yes',
    },
    {
      _id: '36faa3f38deab95a4319157845022776',
      'select-id': 2,
      type: 'answer',
      name: 'No',
      desc: '',
      'test-id': 'compliance-answer-no',
      order: 3,
      slug: 'no',
      commentRequired: true,
    },
    {
      _id: '36faa3f38deab95a43191578450241a1',
      'select-id': 3,
      type: 'answer',
      name: 'Partially Compliant',
      desc: '',
      'test-id': 'compliance-answer-partially-compliant',
      order: 4,
      slug: 'partially-compliant',
      commentRequired: true,
    },
    {
      _id: '36faa3f38deab95a43191578450249f7',
      'select-id': 4,
      type: 'answer',
      name: 'N/A',
      desc: '',
      'test-id': 'compliance-answer-not-applicable',
      order: 5,
      slug: 'not-applicable',
      commentRequired: true,
    },
    {
      _id: '23be888baa7539a68ba0b2229d0017f0',
      type: 'setting',
      name: 'active',
      value: true,
    },
  ];
  return complianceOptions;
// --------------------------------------------------------------------------------------------- //
};
// ============================================================================================= //
