// ============================================================================================= //
module.exports = () => {
  const dateFormat = (daysAgo = 0) => {
    const date = new Date();
    date.setDate(date.getDate() - daysAgo);
    return date.toJSON().split('T')[0];
  };

  const oneDayAgoDate = dateFormat(1);
  const twoDaysAgoDate = dateFormat(2);
  // ------------------------------------------------------------------------------------------- //
  // ------------------------------------------------------------------------------------------- //
  const masterQueue = [
    {
      _id: '633d56c164427500913ae333',
      status: 0,
      attempts: 0,
      index: 0,
      priority: 0,
      mission: 'microserviceElasticSync',
      target: '633d56c164427500913ae332',
      objective: 'microserviceSync_test-about-field-permission__1664964289585',
      command: 'adp.microservice.synchronizeWithElasticSearch',
      params: [
        '633d56c164427500913ae332',
      ],
      added: new Date(`${oneDayAgoDate}T13:53:56.883Z`),
      waited: 0,
      started: 0,
      duration: 0,
      ended: 0,
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        status: 0,
        message: 'Status 0: Waiting...',
        queueStatusLink: 'https://seliius18473.seli.gic.ericsson.se:58081/api/queue/V2.0_bWljcm9zZXJ2aWNlU3luY190ZXN0LWFib3V0LWZpZWxkLXBlcm1pc3Npb25fXzE2NjQ5NjQyODk1ODU=',
      },
    },
    {
      _id: '633d56f764427500913ae3a3',
      status: 0,
      attempts: 0,
      index: 0,
      priority: 0,
      mission: 'documentRefresh',
      target: '4befcc82eebf81c3e1b5242b49001084',
      objective: 'auto-ms-with-mock-artifactory-doc-1__1664964343534',
      command: 'adp.integration.documentRefresh.update',
      params: [
        {
          _id: '4befcc82eebf81c3e1b5242b49001084',
          name: 'Auto MS with Mock Artifactory Doc 1',
          slug: 'auto-ms-with-mock-artifactory-doc-1',
          menu_auto: true,
          repo_urls: {
            development: 'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/',
            release: 'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/',
          },
        },
        'auto-ms-with-mock-artifactory-doc-1__1664964343534',
      ],
      added: new Date(`${oneDayAgoDate}T13:53:56.883Z`),
      waited: 0,
      started: 0,
      duration: 0,
      ended: 0,
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        status: 0,
        message: 'Status 0: Waiting...',
        queueStatusLink: 'https://seliius18473.seli.gic.ericsson.se:58081/api/queue/V2.0_YXV0by1tcy13aXRoLW1vY2stYXJ0aWZhY3RvcnktZG9jLTFfXzE2NjQ5NjQzNDM1MzQ=',
      },
    },
    {
      _id: '633d5aaf28f14e0091bc30d7',
      status: 200,
      attempts: 1,
      index: 0,
      priority: 0,
      mission: 'documentRefresh',
      target: '4befcc82eebf81c3e1b5242b49001084',
      objective: 'auto-ms-with-mock-artifactory-doc-1__1664965295886',
      command: 'adp.integration.documentRefresh.update',
      params: [
        {
          _id: '4befcc82eebf81c3e1b5242b49001084',
          name: 'Auto MS with Mock Artifactory Doc 1',
          slug: 'auto-ms-with-mock-artifactory-doc-1',
          menu_auto: true,
          repo_urls: {
            development: 'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/',
            release: 'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/',
          },
        },
        'auto-ms-with-mock-artifactory-doc-1__1664965295886',
      ],
      added: new Date(`${oneDayAgoDate}T13:53:56.883Z`),
      waited: 1527,
      started: new Date(`${oneDayAgoDate}T10:21:37.415Z`),
      duration: 78,
      ended: new Date(`${oneDayAgoDate}T10:21:37.493Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        dbResponse: {
          _id: '4befcc82eebf81c3e1b5242b49001084',
          name: 'Auto MS with Mock Artifactory Doc 1',
          slug: 'auto-ms-with-mock-artifactory-doc-1',
        },
        yamlErrors: [],
        yamlErrorsQuant: 0,
        yamlWarnings: [],
        yamlWarningsQuant: 0,
      },
      payload: {
        status: 200,
        serverStatusCode: 200,
        name: 'Auto MS with Mock Artifactory Doc 1',
        slug: 'auto-ms-with-mock-artifactory-doc-1',
        versions: 2,
        yamlErrors: {
          development: [],
          release: [],
        },
        yamlErrorsQuant: 0,
        yamlWarnings: {
          development: [],
          release: [],
        },
        yamlWarningsQuant: 0,
        theMenu: {
          auto: {
            development: [
              {
                name: 'Sample 1',
                filepath: '1.0.1/CAS_Deployment_Guide.zip',
                default: true,
                slug: 'sample-1',
              },
              {
                name: 'Sample 2',
                filepath: '1.0.1/test.html',
                slug: 'sample-2',
              },
              {
                name: 'An External',
                external_link: 'https://www.ericsson.se',
                slug: 'an-external',
              },
            ],
            release: [
              {
                version: '1.0.1',
                is_cpi_updated: false,
                documents: [
                  {
                    name: 'Sample 1',
                    filepath: '1.0.1/CAS_Deployment_Guide.zip',
                    default: true,
                    slug: 'sample-1',
                  },
                  {
                    name: 'Sample 2',
                    filepath: '1.0.1/test.html',
                    slug: 'sample-2',
                  },
                  {
                    name: 'An External',
                    external_link: 'https://www.ericsson.se',
                    slug: 'an-external',
                  },
                ],
              },
            ],
          },
        },
      },
    },
    {
      _id: '633d5b8e28f14e0091bc323d',
      status: 200,
      attempts: 1,
      index: 0,
      priority: 0,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965518736',
      command: 'adp.mimer.getProduct',
      params: [
        'APR20135',
        'true',
        '45e7f4f992afe7bbb62a3391e500ffry',
        'auto-ms-mimer__1664965518736',
        null,
      ],
      added: new Date(`${oneDayAgoDate}T10:25:18.737Z`),
      waited: 1331,
      started: new Date(`${oneDayAgoDate}T10:25:20.068Z`),
      duration: 15,
      ended: new Date(`${oneDayAgoDate}T10:25:20.083Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        status: 200,
        queue: 'auto-ms-mimer__1664965518736',
        queueStatusLink: 'https://seliius18473.seli.gic.ericsson.se:58083/api/queue/V2.0_YXV0by1tcy1taW1lcl9fMTY2NDk2NTUxODczNg==',
        statusDescription: 'Product auto-ms-mimer retrieved',
        answerFromRemote: [
          {
            number: 'APR20135',
            product: 'Auto MS Mimer',
            version: '8.3.0',
            url: 'http://seliius18473.seli.gic.ericsson.se:56063/muninserver/api/v1/products/APR20135/versions/8.3.0',
          },
        ],
      },
    },
    {
      _id: '633d5b90f7ec18009703527e',
      status: 200,
      attempts: 1,
      index: 1,
      priority: 0,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965518736',
      command: 'adp.mimer.getVersion',
      params: [
        'APR20135',
        '8.3.0',
        'http://seliius18473.seli.gic.ericsson.se:56063/muninserver/api/v1/products/APR20135/versions/8.3.0',
        '45e7f4f992afe7bbb62a3391e500ffry',
        'auto-ms-mimer__1664965518736',
      ],
      added: new Date(`${oneDayAgoDate}T10:25:20.078Z`),
      waited: 9,
      started: new Date(`${oneDayAgoDate}T10:25:20.087Z`),
      duration: 15,
      ended: new Date(`${oneDayAgoDate}T10:25:20.102Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        830: {
          versionLabel: '8.3.0',
          'release-documents': [
            {
              name: '0360-APR20131/7-6',
              slug: '0360-apr201317-6',
              language: 'Uen',
              revision: 'A',
              external_link: 'http://seliius18473.seli.gic.ericsson.se:56063/eridocserver/d2rest/repositories/eridoca/eridocument/download?number-part=0360-APR20131%2F7-6Uen&revision=A',
              physical_file_name: null,
              physical_file_extension: null,
              physical_file_status: null,
              default: false,
              restricted: false,
              url: 'http://seliius18473.seli.gic.ericsson.se:56063/eridocserver/d2rest/repositories/eridoca/eridocument/download?number-part=0360-APR20131%2F7-6Uen&revision=A',
              doc_route: [
                '/marketplace',
                'auto-ms-mimer',
                'documentation',
                '8.3.0',
                'release-documents',
                '0360-apr201317-6',
              ],
              doc_link: 'https://seliius18473.seli.gic.ericsson.se:58083/api/document/auto-ms-mimer/8.3.0/release-documents/0360-apr201317-6',
              doc_mode: 'download',
              category_name: 'Release Documents',
              category_slug: 'release-documents',
              titlePosition: 0,
              data_retrieved_at: new Date(`${oneDayAgoDate}T10:25:20.097Z`),
            },
          ],
        },
        status: 200,
        statusDescription: 'Version 8.3.0 retrieved',
        answerFromRemote: {
          documents: [
            {
              systemOfRecord: 'Eridoc',
              documentNumber: '0360-APR20131/7-6',
              language: 'Uen',
              revision: 'A',
              documentURL: 'http://seliius18473.seli.gic.ericsson.se:56063/eridocserver/d2rest/repositories/eridoca/eridocument/download?number-part=0360-APR20131%2F7-6Uen&revision=A',
            },
            {
              systemOfRecord: 'Munin',
            },
          ],
        },
      },
    },
    {
      _id: '633d5b90f7ec18009703527f',
      status: 200,
      attempts: 1,
      index: 0,
      priority: 1,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965518736',
      command: 'adp.mimer.savingRawMimerMenu',
      params: [
        '45e7f4f992afe7bbb62a3391e500ffry',
        'true',
      ],
      added: new Date(`${oneDayAgoDate}T10:25:20.080Z`),
      waited: 50,
      started: new Date(`${oneDayAgoDate}T10:25:20.130Z`),
      duration: 10,
      ended: new Date(`${oneDayAgoDate}T10:25:20.140Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        savingRawMimerMenu: true,
      },
    },
    {
      _id: '633d5b90f7ec180097035280',
      status: 200,
      attempts: 1,
      index: 0,
      priority: 2,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965518736',
      command: 'adp.mimer.renderMimerArmMenu',
      params: [
        '45e7f4f992afe7bbb62a3391e500ffry',
        'true',
        'auto-ms-mimer__1664965518736',
      ],
      added: new Date(`${oneDayAgoDate}T10:25:20.082Z`),
      waited: 61,
      started: new Date(`${oneDayAgoDate}T10:25:20.143Z`),
      duration: 7,
      ended: new Date(`${oneDayAgoDate}T10:25:20.150Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        result: true,
      },
    },
    {
      _id: '633d5b90f7ec180097035281',
      status: 200,
      attempts: 1,
      priority: 0,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965518736',
      command: 'adp.mimer.mimerTranslationAction',
      params: [
        '45e7f4f992afe7bbb62a3391e500ffry',
        '0360-APR20131/7-6',
        'A',
        'Uen',
        '8.3.0',
      ],
      added: new Date(`${twoDaysAgoDate}T10:25:20.100Z`),
      waited: 6,
      started: new Date(`${twoDaysAgoDate}T10:25:20.106Z`),
      duration: 17,
      ended: new Date(`${twoDaysAgoDate}T10:25:20.123Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        primDD: {
          documentNumber: '0360-apr201317-6',
          documentName: 'Application Developers Guide',
          decimalClass: 360,
          decimalClassPrefix: 1,
        },
        tableReference: [
          {
            _id: '9yuitdzcvhb2tyghjkj87',
            name: 'Secure Coding Report',
            slug: 'secure-coding-report',
            decimalClass: '0360',
            doc: [
              {
                format: 'Word',
                mode: 'External Link',
                type: [
                  'docx',
                  'doc',
                ],
                render: false,
                newtab: true,
                download: false,
                restricted: true,
              },
            ],
          },
        ],
        documentHeader: {
          status: 200,
          fileName: 'mockFileDoc.docx',
          type: 'docx',
        },
        document: {
          name: 'Secure Coding Report',
          slug: 'secure-coding-report',
          language: 'Uen',
          revision: 'A',
          external_link: 'http://seliius18473.seli.gic.ericsson.se:56063/eridocserver/d2rest/repositories/eridoca/eridocument/download?number-part=0360-APR20131%2F7-6Uen&revision=A',
          physical_file_name: 'mockFileDoc.docx',
          physical_file_extension: 'docx',
          physical_file_status: 200,
          default: false,
          restricted: true,
          url: 'http://seliius18473.seli.gic.ericsson.se:56063/eridocserver/d2rest/repositories/eridoca/eridocument/download?number-part=0360-APR20131%2F7-6Uen&revision=A',
          doc_route: [
            '/marketplace',
            'auto-ms-mimer',
            'documentation',
            '8.3.0',
            'release-documents',
            'secure-coding-report',
          ],
          doc_link: 'http://seliius18473.seli.gic.ericsson.se:56063/eridocserver/d2rest/repositories/eridoca/eridocument/secure-coding-report',
          doc_mode: 'newtab',
          category_name: 'Release Documents',
          category_slug: 'release-documents',
          titlePosition: 0,
          data_retrieved_at: new Date(`${twoDaysAgoDate}T10:25:20.097Z`),
        },
      },
    },
    {
      _id: '633d5b90f7ec180097035282',
      status: 200,
      attempts: 1,
      priority: 0,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965518736',
      command: 'adp.mimer.renderMimerArmMenuVersion',
      params: [
        '45e7f4f992afe7bbb62a3391e500ffry',
        '0.0.0',
        'development',
        [
          'auto',
        ],
        'auto-ms-mimer__1664965518736',
      ],
      added: new Date(`${twoDaysAgoDate}T10:25:20.148Z`),
      waited: 6,
      started: new Date(`${twoDaysAgoDate}T10:25:20.154Z`),
      duration: 6,
      ended: new Date(`${twoDaysAgoDate}T10:25:20.160Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: true,
    },
    {
      _id: '633d5b90f7ec180097035283',
      status: 200,
      attempts: 1,
      priority: 0,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965518736',
      command: 'adp.mimer.renderMimerArmMenuVersion',
      params: [
        '45e7f4f992afe7bbb62a3391e500ffry',
        '0.0.0',
        '8.3.0',
        [
          'mimer',
        ],
        'auto-ms-mimer__1664965518736',
      ],
      added: new Date(`${twoDaysAgoDate}T10:25:20.148Z`),
      waited: 18,
      started: new Date(`${twoDaysAgoDate}T10:25:20.166Z`),
      duration: 5,
      ended: new Date(`${twoDaysAgoDate}T10:25:20.171Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: true,
    },
    {
      _id: '633d5b90f7ec180097035284',
      status: 200,
      attempts: 1,
      priority: 0,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965518736',
      command: 'adp.mimer.renderMimerArmMenuFinisher',
      params: [
        '45e7f4f992afe7bbb62a3391e500ffry',
      ],
      added: new Date(`${twoDaysAgoDate}T10:25:20.148Z`),
      waited: 28,
      started: new Date(`${twoDaysAgoDate}T10:25:20.176Z`),
      duration: 9,
      ended: new Date(`${twoDaysAgoDate}T10:25:20.185Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: true,
    },
    {
      _id: '633d5b9328f14e0091bc323e',
      status: 200,
      attempts: 1,
      index: 0,
      priority: 0,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965523166',
      command: 'adp.mimer.getProduct',
      params: [
        'APR20135',
        'true',
        '45e7f4f992afe7bbb62a3391e500ffry',
        'auto-ms-mimer__1664965523166',
        null,
      ],
      added: new Date(`${twoDaysAgoDate}T10:25:23.167Z`),
      waited: 1910,
      started: new Date(`${twoDaysAgoDate}T10:25:25.077Z`),
      duration: 22,
      ended: new Date(`${twoDaysAgoDate}T10:25:25.099Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        status: 200,
        queue: 'auto-ms-mimer__1664965523166',
        queueStatusLink: 'https://seliius18473.seli.gic.ericsson.se:58083/api/queue/V2.0_YXV0by1tcy1taW1lcl9fMTY2NDk2NTUyMzE2Ng==',
        statusDescription: 'Product auto-ms-mimer retrieved',
        answerFromRemote: [
          {
            number: 'APR20135',
            product: 'Auto MS Mimer',
            version: '8.3.0',
            url: 'http://seliius18473.seli.gic.ericsson.se:56063/muninserver/api/v1/products/APR20135/versions/8.3.0',
          },
        ],
      },
    },
    {
      _id: '633d5b95f7ec180097035285',
      status: 200,
      attempts: 1,
      index: 1,
      priority: 0,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965523166',
      command: 'adp.mimer.getVersion',
      params: [
        'APR20135',
        '8.3.0',
        'http://seliius18473.seli.gic.ericsson.se:56063/muninserver/api/v1/products/APR20135/versions/8.3.0',
        '45e7f4f992afe7bbb62a3391e500ffry',
        'auto-ms-mimer__1664965523166',
      ],
      added: new Date(`${twoDaysAgoDate}T10:25:25.094Z`),
      waited: 8,
      started: new Date(`${twoDaysAgoDate}T10:25:25.102Z`),
      duration: 20,
      ended: new Date(`${twoDaysAgoDate}T10:25:25.122Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        830: {
          versionLabel: '8.3.0',
          'release-documents': [
            {
              name: '0360-APR20131/7-6',
              slug: '0360-apr201317-6',
              language: 'Uen',
              revision: 'A',
              external_link: 'http://seliius18473.seli.gic.ericsson.se:56063/eridocserver/d2rest/repositories/eridoca/eridocument/download?number-part=0360-APR20131%2F7-6Uen&revision=A',
              physical_file_name: null,
              physical_file_extension: null,
              physical_file_status: null,
              default: false,
              restricted: false,
              url: 'http://seliius18473.seli.gic.ericsson.se:56063/eridocserver/d2rest/repositories/eridoca/eridocument/download?number-part=0360-APR20131%2F7-6Uen&revision=A',
              doc_route: [
                '/marketplace',
                'auto-ms-mimer',
                'documentation',
                '8.3.0',
                'release-documents',
                '0360-apr201317-6',
              ],
              doc_link: 'https://seliius18473.seli.gic.ericsson.se:58083/api/document/auto-ms-mimer/8.3.0/release-documents/0360-apr201317-6',
              doc_mode: 'download',
              category_name: 'Release Documents',
              category_slug: 'release-documents',
              titlePosition: 0,
              data_retrieved_at: new Date(`${twoDaysAgoDate}T10:25:25.118Z`),
            },
          ],
        },
        status: 200,
        statusDescription: 'Version 8.3.0 retrieved',
        answerFromRemote: {
          documents: [
            {
              systemOfRecord: 'Eridoc',
              documentNumber: '0360-APR20131/7-6',
              language: 'Uen',
              revision: 'A',
              documentURL: 'http://seliius18473.seli.gic.ericsson.se:56063/eridocserver/d2rest/repositories/eridoca/eridocument/download?number-part=0360-APR20131%2F7-6Uen&revision=A',
            },
            {
              systemOfRecord: 'Munin',
            },
          ],
        },
      },
    },
    {
      _id: '633d5b95f7ec180097035286',
      status: 200,
      attempts: 1,
      index: 0,
      priority: 1,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965523166',
      command: 'adp.mimer.savingRawMimerMenu',
      params: [
        '45e7f4f992afe7bbb62a3391e500ffry',
        'true',
      ],
      added: new Date(`${twoDaysAgoDate}T10:25:25.096Z`),
      waited: 54,
      started: new Date(`${twoDaysAgoDate}T10:25:25.150Z`),
      duration: 8,
      ended: new Date(`${twoDaysAgoDate}T10:25:25.158Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        savingRawMimerMenu: true,
      },
    },
    {
      _id: '633d5b95f7ec180097035287',
      status: 200,
      attempts: 1,
      index: 0,
      priority: 2,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965523166',
      command: 'adp.mimer.renderMimerArmMenu',
      params: [
        '45e7f4f992afe7bbb62a3391e500ffry',
        'true',
        'auto-ms-mimer__1664965523166',
      ],
      added: new Date(`${twoDaysAgoDate}T10:25:25.098Z`),
      waited: 63,
      started: new Date(`${twoDaysAgoDate}T10:25:25.161Z`),
      duration: 7,
      ended: new Date(`${twoDaysAgoDate}T10:25:25.168Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        result: true,
      },
    },
    {
      _id: '633d5b95f7ec180097035288',
      status: 200,
      attempts: 1,
      priority: 0,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965523166',
      command: 'adp.mimer.mimerTranslationAction',
      params: [
        '45e7f4f992afe7bbb62a3391e500ffry',
        '0360-APR20131/7-6',
        'A',
        'Uen',
        '8.3.0',
      ],
      added: new Date(`${twoDaysAgoDate}T10:25:25.120Z`),
      waited: 7,
      started: new Date(`${twoDaysAgoDate}T10:25:25.127Z`),
      duration: 20,
      ended: new Date(`${twoDaysAgoDate}T10:25:25.147Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        primDD: {
          documentNumber: '0360-apr201317-6',
          documentName: 'Pri',
          decimalClass: 360,
          decimalClassPrefix: 1,
        },
        tableReference: [
          {
            _id: '9yuitdzcvhb2tyghjkj87',
            name: 'Secure Coding Report',
            slug: 'secure-coding-report',
            decimalClass: '0360',
            doc: [
              {
                format: 'Word',
                mode: 'External Link',
                type: [
                  'docx',
                  'doc',
                ],
                render: false,
                newtab: true,
                download: false,
                restricted: true,
              },
            ],
          },
        ],
        documentHeader: {
          status: 200,
          fileName: 'testHtml.zip',
          type: 'zip',
        },
        document: {
          name: 'Secure Coding Report',
          slug: 'secure-coding-report',
          language: 'Uen',
          revision: 'A',
          external_link: 'http://seliius18473.seli.gic.ericsson.se:56063/eridocserver/d2rest/repositories/eridoca/eridocument/download?number-part=0360-APR20131%2F7-6Uen&revision=A',
          physical_file_name: 'testHtml.zip',
          physical_file_extension: 'zip',
          physical_file_status: 200,
          default: false,
          restricted: true,
          url: 'http://seliius18473.seli.gic.ericsson.se:56063/eridocserver/d2rest/repositories/eridoca/eridocument/download?number-part=0360-APR20131%2F7-6Uen&revision=A',
          doc_route: [
            '/marketplace',
            'auto-ms-mimer',
            'documentation',
            '8.3.0',
            'release-documents',
            'secure-coding-report',
          ],
          doc_link: 'https://seliius18473.seli.gic.ericsson.se:58083/api/document/auto-ms-mimer/8.3.0/release-documents/secure-coding-report',
          doc_mode: 'newtab',
          category_name: 'Release Documents',
          category_slug: 'release-documents',
          titlePosition: 0,
          data_retrieved_at: new Date(`${twoDaysAgoDate}T10:25:25.118Z`),
        },
      },
    },
    {
      _id: '633d5b95f7ec180097035289',
      status: 200,
      attempts: 1,
      priority: 0,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965523166',
      command: 'adp.mimer.renderMimerArmMenuVersion',
      params: [
        '45e7f4f992afe7bbb62a3391e500ffry',
        '0.0.0',
        'development',
        [
          'auto',
        ],
        'auto-ms-mimer__1664965523166',
      ],
      added: new Date(`${twoDaysAgoDate}T10:25:25.166Z`),
      waited: 5,
      started: new Date(`${twoDaysAgoDate}T10:25:25.171Z`),
      duration: 6,
      ended: new Date(`${twoDaysAgoDate}T10:25:25.177Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: true,
    },
    {
      _id: '633d5b95f7ec18009703528a',
      status: 200,
      attempts: 1,
      priority: 0,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965523166',
      command: 'adp.mimer.renderMimerArmMenuVersion',
      params: [
        '45e7f4f992afe7bbb62a3391e500ffry',
        '0.0.0',
        '8.3.0',
        [
          'mimer',
        ],
        'auto-ms-mimer__1664965523166',
      ],
      added: new Date(`${twoDaysAgoDate}T10:25:25.166Z`),
      waited: 15,
      started: new Date(`${twoDaysAgoDate}T10:25:25.181Z`),
      duration: 6,
      ended: new Date(`${twoDaysAgoDate}T10:25:25.187Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: true,
    },
    {
      _id: '633d5b95f7ec18009703528b',
      status: 200,
      attempts: 1,
      priority: 0,
      mission: 'mimerDocumentUpdate',
      target: '45e7f4f992afe7bbb62a3391e500ffry',
      objective: 'auto-ms-mimer__1664965523166',
      command: 'adp.mimer.renderMimerArmMenuFinisher',
      params: [
        '45e7f4f992afe7bbb62a3391e500ffry',
      ],
      added: new Date(`${twoDaysAgoDate}T10:25:25.166Z`),
      waited: 28,
      started: new Date(`${twoDaysAgoDate}T10:25:25.194Z`),
      duration: 7,
      ended: new Date(`${twoDaysAgoDate}T10:25:25.201Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: true,
    },
    {
      _id: '633d5b1c28f14e0091bc3112',
      status: 200,
      attempts: 1,
      index: 0,
      priority: 0,
      mission: 'microserviceElasticSync',
      target: '45e7f4f992afe7bbb62a3391e5019b57',
      objective: 'microserviceSync_auto-ms-test-5__1664965404031',
      command: 'adp.microservice.synchronizeWithElasticSearch',
      params: [
        '45e7f4f992afe7bbb62a3391e5019b57',
        null,
      ],
      added: new Date(`${twoDaysAgoDate}T10:23:24.032Z`),
      waited: 1018,
      started: new Date(`${twoDaysAgoDate}T10:23:25.050Z`),
      duration: 47,
      ended: new Date(`${twoDaysAgoDate}T10:23:25.097Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        id: '45e7f4f992afe7bbb62a3391e5019b57',
        slug: 'auto-ms-test-5',
        action: 'Updated',
        timerMS: 41,
      },
    },
    {
      _id: '633d5b1c28f14e0091bc3113',
      status: 200,
      attempts: 1,
      index: 0,
      priority: 2,
      mission: 'microserviceDocumentsElasticSync',
      target: '45e7f4f992afe7bbb62a3391e5019b57',
      objective: 'documentSync_auto-ms-test-5__1664965404031',
      command: 'adp.microservice.synchronizeDocumentsWithElasticSearch.add',
      params: [
        [
          '45e7f4f992afe7bbb62a3391e5019b57',
        ],
        null,
        null,
        'documentSync_auto-ms-test-5__1664965404031',
      ],
      added: new Date(`${twoDaysAgoDate}T10:23:24.037Z`),
      waited: 1309,
      started: new Date(`${twoDaysAgoDate}T10:23:25.346Z`),
      duration: 13,
      ended: new Date(`${twoDaysAgoDate}T10:23:25.359Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        queueStatusLink: 'https://seliius18473.seli.gic.ericsson.se:58083/api/queue/V2.0_ZG9jdW1lbnRTeW5jX2F1dG8tbXMtdGVzdC01X18xNjY0OTY1NDA0MDMx',
      },
    },
    {
      _id: '633d5c8f28f14e0091bc33bf',
      status: 200,
      attempts: 1,
      index: 0,
      priority: 0,
      mission: 'documentRefresh',
      target: '17e57f6cea1b5a673f8775e6cf023346',
      objective: 'document-refresh-microservice-cpi-true__1664965775216',
      command: 'adp.integration.documentRefresh.update',
      params: [
        {
          _id: '17e57f6cea1b5a673f8775e6cf023346',
          name: 'Document Refresh Microservice CPI true',
          slug: 'document-refresh-microservice-cpi-true',
          menu_auto: true,
          repo_urls: {
            development: 'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/',
            release: 'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/',
          },
        },
        'document-refresh-microservice-cpi-true__1664965775216',
      ],
      added: new Date(`${twoDaysAgoDate}T10:29:35.217Z`),
      waited: 55,
      started: new Date(`${twoDaysAgoDate}T10:29:35.272Z`),
      duration: 87,
      ended: new Date(`${twoDaysAgoDate}T10:29:35.359Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        dbResponse: {
          _id: '17e57f6cea1b5a673f8775e6cf023346',
          name: 'Document Refresh Microservice CPI true',
          slug: 'document-refresh-microservice-cpi-true',
        },
        yamlErrors: [],
        yamlErrorsQuant: 0,
        yamlWarnings: [],
        yamlWarningsQuant: 0,
      },
      payload: {
        status: 200,
        serverStatusCode: 200,
        name: 'Document Refresh Microservice CPI true',
        slug: 'document-refresh-microservice-cpi-true',
        versions: 2,
        yamlErrors: {
          development: [],
          release: [],
        },
        yamlErrorsQuant: 0,
        yamlWarnings: {
          development: [],
          release: [],
        },
        yamlWarningsQuant: 0,
        theMenu: {
          auto: {
            development: [
              {
                name: 'Sample 1',
                filepath: '1.0.1/CAS_Deployment_Guide.zip',
                default: true,
                slug: 'sample-1',
              },
              {
                name: 'Sample 2',
                filepath: '1.0.1/test.html',
                slug: 'sample-2',
              },
              {
                name: 'An External',
                external_link: 'https://www.ericsson.se',
                slug: 'an-external',
              },
            ],
            release: [
              {
                version: '1.0.1',
                is_cpi_updated: true,
                documents: [
                  {
                    name: 'Sample 1',
                    filepath: '1.0.1/CAS_Deployment_Guide.zip',
                    default: true,
                    slug: 'sample-1',
                  },
                  {
                    name: 'Sample 2',
                    filepath: '1.0.1/test.html',
                    slug: 'sample-2',
                  },
                  {
                    name: 'An External',
                    external_link: 'https://www.ericsson.se',
                    slug: 'an-external',
                  },
                ],
              },
            ],
          },
        },
      },
    },
    {
      _id: '633d5c8f28f14e0091bc33c0',
      status: 200,
      attempts: 1,
      index: 0,
      priority: 1,
      mission: 'microserviceDocumentsElasticSync',
      target: '17e57f6cea1b5a673f8775e6cf023346',
      objective: 'document-refresh-microservice-cpi-true__1664965775222',
      command: 'adp.microservice.synchronizeDocumentsWithElasticSearch.add',
      params: [
        [
          '17e57f6cea1b5a673f8775e6cf023346',
        ],
        null,
        null,
        'document-refresh-microservice-cpi-true__1664965775222',
      ],
      added: new Date(`${twoDaysAgoDate}T10:29:35.224Z`),
      waited: 286,
      started: new Date(`${twoDaysAgoDate}T10:29:35.510Z`),
      duration: 49,
      ended: new Date(`${twoDaysAgoDate}T10:29:35.559Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        queueStatusLink: 'https://seliius18473.seli.gic.ericsson.se:58083/api/queue/V2.0_ZG9jdW1lbnQtcmVmcmVzaC1taWNyb3NlcnZpY2UtY3BpLXRydWVfXzE2NjQ5NjU3NzUyMjI=',
      },
    },
    {
      _id: '633d5c8ff7ec18009703543e',
      status: 200,
      attempts: 1,
      index: 1,
      priority: 0,
      mission: 'documentRefresh',
      target: '17e57f6cea1b5a673f8775e6cf023346',
      objective: 'document-refresh-microservice-cpi-true__1664965775216',
      command: 'adp.integration.documentRefreshPerVersion',
      params: [
        '17e57f6cea1b5a673f8775e6cf023346',
        'document-refresh-microservice-cpi-true',
        'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/1.0.1.yaml',
        '1.0.1',
        'development',
      ],
      added: new Date(`${twoDaysAgoDate}T10:29:35.324Z`),
      waited: 44,
      started: new Date(`${twoDaysAgoDate}T10:29:35.368Z`),
      duration: 21,
      ended: new Date(`${twoDaysAgoDate}T10:29:35.389Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        version: 'development',
        yamlUrl: 'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/1.0.1.yaml',
        yamlRaw: 'version: 1.0.1\nis_cpi_updated: true\ndocuments:\n - name: Sample 1\n   filepath: \'1.0.1/CAS_Deployment_Guide.zip\'\n   default: true\n - name: Sample 2\n   filepath: \'1.0.1/test.html\'\n - name: An External\n   external-link: https://www.ericsson.se\n',
        yamlParsed: {
          version: '1.0.1',
          is_cpi_updated: true,
          documents: [
            {
              name: 'Sample 1',
              filepath: '1.0.1/CAS_Deployment_Guide.zip',
              default: true,
              slug: 'sample-1',
            },
            {
              name: 'Sample 2',
              filepath: '1.0.1/test.html',
              slug: 'sample-2',
            },
            {
              name: 'An External',
              external_link: 'https://www.ericsson.se',
              slug: 'an-external',
            },
          ],
        },
        dbResponse: {
          _id: '17e57f6cea1b5a673f8775e6cf023346',
          slug: 'document-refresh-microservice-cpi-true',
        },
        yamlErrors: {
          development: [],
          release: [],
        },
        yamlErrorsQuant: 0,
        yamlWarnings: {
          development: [],
          release: [],
        },
        yamlWarningsQuant: 0,
      },
    },
    {
      _id: '633d5c8ff7ec18009703543f',
      status: 200,
      attempts: 1,
      index: 2,
      priority: 0,
      mission: 'documentRefresh',
      target: '17e57f6cea1b5a673f8775e6cf023346',
      objective: 'document-refresh-microservice-cpi-true__1664965775216',
      command: 'adp.integration.documentRefreshPerVersion',
      params: [
        '17e57f6cea1b5a673f8775e6cf023346',
        'document-refresh-microservice-cpi-true',
        'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/1.0.1.yaml',
        '1.0.1',
        'release',
      ],
      added: new Date(`${twoDaysAgoDate}T10:29:35.353Z`),
      waited: 43,
      started: new Date(`${twoDaysAgoDate}T10:29:35.396Z`),
      duration: 18,
      ended: new Date(`${twoDaysAgoDate}T10:29:35.414Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        version: '1.0.1',
        yamlUrl: 'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/1.0.1.yaml',
        yamlRaw: 'version: 1.0.1\nis_cpi_updated: true\ndocuments:\n - name: Sample 1\n   filepath: \'1.0.1/CAS_Deployment_Guide.zip\'\n   default: true\n - name: Sample 2\n   filepath: \'1.0.1/test.html\'\n - name: An External\n   external-link: https://www.ericsson.se\n',
        yamlParsed: {
          version: '1.0.1',
          is_cpi_updated: true,
          documents: [
            {
              name: 'Sample 1',
              filepath: '1.0.1/CAS_Deployment_Guide.zip',
              default: true,
              slug: 'sample-1',
            },
            {
              name: 'Sample 2',
              filepath: '1.0.1/test.html',
              slug: 'sample-2',
            },
            {
              name: 'An External',
              external_link: 'https://www.ericsson.se',
              slug: 'an-external',
            },
          ],
        },
        dbResponse: {
          _id: '17e57f6cea1b5a673f8775e6cf023346',
          slug: 'document-refresh-microservice-cpi-true',
        },
        yamlErrors: {
          development: [],
          release: [],
        },
        yamlErrorsQuant: 0,
        yamlWarnings: {
          development: [],
          release: [],
        },
        yamlWarningsQuant: 0,
      },
    },
    {
      _id: '633d5c8ff7ec180097035441',
      status: 200,
      attempts: 1,
      index: 0,
      priority: 0,
      mission: 'documentRefresh',
      target: '17e57f6cea1b5a673f8775e6cf023346',
      objective: 'document-refresh-microservice-cpi-true__1664965775216_MAIN',
      command: 'adp.integration.documentRefresh.clearCache',
      params: [
        '17e57f6cea1b5a673f8775e6cf023346',
        'document-refresh-microservice-cpi-true',
      ],
      added: new Date(`${twoDaysAgoDate}T10:29:35.494Z`),
      waited: 849,
      started: new Date(`${twoDaysAgoDate}T10:29:36.343Z`),
      duration: 78,
      ended: new Date(`${twoDaysAgoDate}T10:29:36.421Z`),
      type: 'queueItem',
      runner: 'MAIN',
      data: 'Cache of [ 17e57f6cea1b5a673f8775e6cf023346 / document-refresh-microservice-cpi-true ] asset and documents cleared!',
    },
    {
      _id: '633d5c91f7ec180097035448',
      status: 200,
      attempts: 1,
      index: 1,
      priority: 0,
      mission: 'documentRefresh',
      target: '17e57f6cea1b5a673f8775e6cf023346',
      objective: 'document-refresh-microservice-cpi-true__1664965776340',
      command: 'adp.integration.documentRefreshPerVersion',
      params: [
        '17e57f6cea1b5a673f8775e6cf023346',
        'document-refresh-microservice-cpi-true',
        'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/1.0.1.yaml',
        '1.0.1',
        'development',
      ],
      added: new Date(`${twoDaysAgoDate}T10:29:37.811Z`),
      waited: 27,
      started: new Date(`${twoDaysAgoDate}T10:29:37.838Z`),
      duration: 23,
      ended: new Date(`${twoDaysAgoDate}T10:29:37.861Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        version: 'development',
        yamlUrl: 'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/1.0.1.yaml',
        yamlRaw: 'version: 1.0.1\ndocuments:\n - name: Sample 1\n   filepath: \'1.0.1/CAS_Deployment_Guide.zip\'\n   default: true\n - name: Sample 2\n   filepath: \'1.0.1/test.html\'\n - name: An External\n   external-link: https://www.ericsson.se\n',
        yamlParsed: {
          version: '1.0.1',
          documents: [
            {
              name: 'Sample 1',
              filepath: '1.0.1/CAS_Deployment_Guide.zip',
              default: true,
              slug: 'sample-1',
            },
            {
              name: 'Sample 2',
              filepath: '1.0.1/test.html',
              slug: 'sample-2',
            },
            {
              name: 'An External',
              external_link: 'https://www.ericsson.se',
              slug: 'an-external',
            },
          ],
        },
        dbResponse: {
          _id: '17e57f6cea1b5a673f8775e6cf023346',
          slug: 'document-refresh-microservice-cpi-true',
        },
        yamlErrors: {
          development: [],
          release: [],
        },
        yamlErrorsQuant: 0,
        yamlWarnings: {
          development: [],
          release: [],
        },
        yamlWarningsQuant: 0,
      },
    },
    {
      _id: '633d5c91f7ec18009703544c',
      status: 200,
      attempts: 1,
      index: 0,
      priority: 0,
      mission: 'documentRefresh',
      target: '17e57f6cea1b5a673f8775e6cf023346',
      objective: 'document-refresh-microservice-cpi-true__1664965776340_MAIN',
      command: 'adp.integration.documentRefresh.clearCache',
      params: [
        '17e57f6cea1b5a673f8775e6cf023346',
        'document-refresh-microservice-cpi-true',
      ],
      added: new Date(`${twoDaysAgoDate}T10:29:37.955Z`),
      waited: 841,
      started: new Date(`${twoDaysAgoDate}T10:29:38.796Z`),
      duration: 9,
      ended: new Date(`${twoDaysAgoDate}T10:29:38.805Z`),
      type: 'queueItem',
      runner: 'MAIN',
      data: 'Cache of [ 17e57f6cea1b5a673f8775e6cf023346 / document-refresh-microservice-cpi-true ] asset and documents cleared!',
    },
    {
      _id: '633d56f764427500913ae3a1',
      status: 500,
      attempts: 1,
      index: 0,
      priority: 0,
      mission: 'documentRefresh',
      target: '4befcc82eebf81c3e1b5242b49001084',
      objective: 'auto-ms-with-mock-artifactory-doc-1__1664964343123',
      command: 'adp.integration.documentRefresh.update',
      params: [
        {
          _id: '4befcc82eebf81c3e1b5242b49001084',
          name: 'Auto MS with Mock Artifactory Doc 1',
          slug: 'auto-ms-with-mock-artifactory-doc-1',
          menu_auto: true,
          repo_urls: {
            development: 'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/',
            release: 'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/',
          },
        },
        'auto-ms-with-mock-artifactory-doc-1__1664964343123',
      ],
      added: new Date(`${twoDaysAgoDate}T13:53:56.883Z`),
      waited: 82288793,
      started: new Date(`${twoDaysAgoDate}T12:45:25.676Z`),
      duration: 35,
      ended: new Date(`${twoDaysAgoDate}T12:45:25.711Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        status: 500,
        error: '{"stack":"Error: {\\"development\\":[\\"Artifactory location not found\\"],\\"release\\":[\\"Artifactory location not found\\"]}\\n    at getMenuFromRepos (/home/zgarsri/repos/be/adp/adp_backend/src/artifactoryRepo/artifactoryRepo.js:512:11)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\\n    at async updateService (/home/zgarsri/repos/be/adp/adp_backend/src/artifactoryRepo/artifactoryRepo.js:578:13)\\n    at async update (/home/zgarsri/repos/be/adp/adp_backend/src/integration/documentRefresh.js:153:5)","message":"{\\"development\\":[\\"Artifactory location not found\\"],\\"release\\":[\\"Artifactory location not found\\"]}"}',
        ms: {
          _id: '4befcc82eebf81c3e1b5242b49001084',
          name: 'Auto MS with Mock Artifactory Doc 1',
          slug: 'auto-ms-with-mock-artifactory-doc-1',
          menu_auto: true,
          repo_urls: {
            development: 'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/',
            release: 'https://seliius18473.seli.gic.ericsson.se:58090/notify/mockartifactory/local/dynamic/',
          },
        },
        objective: 'auto-ms-with-mock-artifactory-doc-1__1664964343123',
        dbResponse: {
          _id: '4befcc82eebf81c3e1b5242b49001084',
          name: 'Auto MS with Mock Artifactory Doc 1',
          slug: 'auto-ms-with-mock-artifactory-doc-1',
        },
        yamlErrors: [
          'Fatal Error',
        ],
        yamlErrorsQuant: 1,
        yamlWarnings: [],
        yamlWarningsQuant: 0,
      },
      payload: {
        status: 404,
        serverStatusCode: 404,
        yamlErrors: {
          development: [
            'Artifactory location not found',
          ],
          release: [
            'Artifactory location not found',
          ],
        },
        yamlErrorsQuant: 2,
        yamlWarnings: {
          development: [],
          release: [],
        },
        yamlWarningsQuant: 0,
      },
    },
    {
      _id: '64754f8da339ba009095e722',
      status: 200,
      attempts: 1,
      index: 2,
      priority: 0,
      mission: 'documentRefresh',
      target: '4befcc82eebf81c3e1b5242b49001084',
      objective: 'auto-ms-with-mock-artifactory-doc-1__1664964341234',
      command: 'adp.integration.documentRefreshPerVersion',
      params: [
        '5c2941141c64cfbcea47e8b16009e116',
        'certificate-management',
        'https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-adp-certificate-management-docs-released-generic-local/documents/1.3.0.yaml',
        '1.3.0',
        'release',
      ],
      added: new Date(`${twoDaysAgoDate}T01:21:17.737Z`),
      waited: 171,
      started: new Date(`${twoDaysAgoDate}T01:21:17.908Z`),
      duration: 498,
      ended: new Date(`${twoDaysAgoDate}T01:21:18.406Z`),
      type: 'queueItem',
      runner: 'WORKER',
      data: {
        version: '1.3.0',
        yamlUrl: 'https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-adp-certificate-management-docs-released-generic-local/documents/1.3.0.yaml',
        yamlRaw: 'version: 1.3.0\ndocuments:\n- name: Service User Guide\n  filepath: 1.3.0/user-guide.zip\n- name: API Documentation\n  filepath: 1.3.0/CertM_Service_Interface_Description_HTML.zip\n- name: Inner Source README\n  external-link: https://gerrit-gamma.gic.ericsson.se/plugins/gitiles/adp-sec/sec-certm/+/v1.3.0+63/README.md\n- name: Contributing Guideline\n  external-link: \'https://gerrit-gamma.gic.ericsson.se/plugins/gitiles/adp-sec/sec-certm/+/v1.3.0+63/CONTRIBUTING.md \'\n- name: Test Specification\n  filepath: 1.3.0/CertM_Service_Test_Specification.html\n- name: Test Report\n  external-link: https://erilink.ericsson.se/eridoc/erl/objectId/09004cffc4864750?docno=15283-APR20111/1-4Uen&format=html\n- name: Software Vendor List (SVL)\n  external-link: https://erilink.ericsson.se/eridoc/erl/objectId/09004cffc484878e?docno=24050-APR20111/1Uen&format=excel12mebook\n- name: Vulnerability Analysis Report\n  external-link: https://erilink.ericsson.se/eridoc/erl/objectId/09004cffc4859229?docno=1/1597-APR20111/1Uen&format=md\n  restricted: true\n- name: Risk Assessment & Privacy Impact Assessment\n  external-link: https://erilink.ericsson.se/eridoc/erl/objectId/09004cffc3f11728?docno=1/00664-APR20111/1Uen&format=msw12me\n  restricted: true\n- name: Product Revision Information (PRI)\n  external-link: https://erilink.ericsson.se/eridoc/erl/objectId/09004cffc47e2f8f?docno=10921-APR20111/1-4Uen&action=approved&format=msw12\n',
        yamlParsed: {
          version: '1.3.0',
          documents: [
            {
              name: 'Service User Guide',
              filepath: '1.3.0/user-guide.zip',
              slug: 'service-user-guide',
              default: true,
            },
            {
              name: 'API Documentation',
              filepath: '1.3.0/CertM_Service_Interface_Description_HTML.zip',
              slug: 'api-documentation',
            },
            {
              name: 'Inner Source README',
              external_link: 'https://gerrit-gamma.gic.ericsson.se/plugins/gitiles/adp-sec/sec-certm/+/v1.3.0+63/README.md',
              slug: 'inner-source-readme',
            },
            {
              name: 'Contributing Guideline',
              external_link: 'https://gerrit-gamma.gic.ericsson.se/plugins/gitiles/adp-sec/sec-certm/+/v1.3.0+63/CONTRIBUTING.md ',
              slug: 'contributing-guideline',
            },
            {
              name: 'Test Specification',
              filepath: '1.3.0/CertM_Service_Test_Specification.html',
              slug: 'test-specification',
            },
            {
              name: 'Test Report',
              external_link: 'https://erilink.ericsson.se/eridoc/erl/objectId/09004cffc4864750?docno=15283-APR20111/1-4Uen&format=html',
              slug: 'test-report',
            },
            {
              name: 'Software Vendor List (SVL)',
              external_link: 'https://erilink.ericsson.se/eridoc/erl/objectId/09004cffc484878e?docno=24050-APR20111/1Uen&format=excel12mebook',
              slug: 'software-vendor-list-svl',
            },
            {
              name: 'Vulnerability Analysis Report',
              restricted: true,
              external_link: 'https://erilink.ericsson.se/eridoc/erl/objectId/09004cffc4859229?docno=1/1597-APR20111/1Uen&format=md',
              slug: 'vulnerability-analysis-report',
            },
            {
              name: 'Risk Assessment & Privacy Impact Assessment',
              restricted: true,
              external_link: 'https://erilink.ericsson.se/eridoc/erl/objectId/09004cffc3f11728?docno=1/00664-APR20111/1Uen&format=msw12me',
              slug: 'risk-assessment-privacy-impact-assessment',
            },
            {
              name: 'Product Revision Information (PRI)',
              external_link: 'https://erilink.ericsson.se/eridoc/erl/objectId/09004cffc47e2f8f?docno=10921-APR20111/1-4Uen&action=approved&format=msw12',
              slug: 'product-revision-information-pri',
            },
          ],
        },
        dbResponse: {
          _id: '5c2941141c64cfbcea47e8b16009e116',
          slug: 'certificate-management',
        },
        yamlErrors: {
          development: [],
          release: [],
        },
        yamlErrorsQuant: 0,
        yamlWarnings: {
          development: [],
          release: [
            'The \'is_cpi_updated\' attribute is missing on \'1.3.0\'. Please provide a boolean to indicate if CPI documentation is updated',
          ],
        },
        yamlWarningsQuant: 1,
      },
    },
  ];
  return masterQueue;
// --------------------------------------------------------------------------------------------- //
};
// ============================================================================================= //
