module.exports = () => {
  const primeDDTable = [
    {
      _id: '2twrsfdghy46758itfyhj',
      name: 'API Specification',
      slug: 'api-specification',
      decimalClass: '15519',
      doc: [
        {
          format: 'Zipped HTML',
          mode: 'Direct rendering',
          type: ['html', 'zip'],
          render: true,
          newtab: false,
          download: false,
          restricted: false,
        },
      ],
    },
    {
      _id: 'rtsdfgcyg8u809po8erysdtfyguhi',
      name: 'Application Developers Guide',
      slug: 'application-developers-guide',
      decimalClass: '19817',
      doc: [
        {
          format: 'Zipped HTML',
          mode: 'Direct rendering',
          type: ['html', 'zip'],
          render: true,
          newtab: false,
          download: false,
          restricted: false,
        },
        {
          format: 'Word/PDF',
          mode: 'External Link',
          type: ['docx', 'doc', 'pdf'],
          render: false,
          newtab: false,
          download: true,
          restricted: false,
        },
      ],
    },
    {
      _id: '4567809dtfghi786475yhbdsgfh567i8',
      name: 'Characteristics Summary Report',
      slug: 'characteristics-summary-report',
      decimalClass: '15283',
      doc: [
        {
          format: 'Zipped HTML',
          mode: 'Direct rendering',
          type: ['html', 'zip'],
          render: true,
          newtab: false,
          download: false,
          restricted: false,
        },
      ],
    },
    {
      _id: '6755rdsdfg89578656wsrxcghk3',
      name: 'PRI',
      slug: 'pri',
      decimalClass: '10921',
      doc: [
        {
          format: 'Zipped HTML',
          mode: 'Direct rendering',
          type: ['html', 'zip'],
          render: true,
          newtab: false,
          download: false,
          restricted: false,
        },
        {
          format: 'Word/PDF',
          mode: 'External Link',
          type: ['docx', 'doc', 'pdf'],
          render: false,
          newtab: false,
          download: true,
          restricted: false,
        },
      ],
    },
    {
      _id: '09876aesdgh13254edtfygh09oihjl0',
      name: 'Risk Assessment & Privacy Impact Assessment',
      slug: 'risk-assessment-privacy-impact-assessment',
      decimalClass: '00664',
      doc: [
        {
          format: 'Word',
          mode: 'External Link',
          type: ['docx', 'doc'],
          render: false,
          newtab: true,
          download: false,
          restricted: true,
        },
      ],
    },
    {
      _id: '9yuitdzcvhb2tyghjkj87',
      name: 'Secure Coding Report',
      slug: 'secure-coding-report',
      decimalClass: '0360',
      doc: [
        {
          format: 'Word',
          mode: 'External Link',
          type: ['docx', 'doc'],
          render: false,
          newtab: true,
          download: false,
          restricted: true,
        },
      ],
    },
    {
      _id: '3e6dytfghjjophvg8790',
      name: 'Security Tool Scan Report',
      slug: 'security-tool-scan-report',
      decimalClass: '15283',
      doc: [
        {
          format: 'TAR/ZIP',
          mode: 'External Link',
          type: ['tar', 'zip'],
          render: false,
          newtab: true,
          download: false,
          restricted: true,
        },
      ],
    },
    {
      _id: '9iuwrsdfghij235fvjlk6y3',
      name: 'Test/Verification Report',
      slug: 'test-verification-report',
      decimalClass: '15283',
      doc: [
        {
          format: 'Zipped HTML',
          mode: 'Direct rendering',
          type: ['html', 'zip'],
          render: true,
          newtab: false,
          download: false,
          restricted: false,
        },
        {
          format: 'Word/PDF',
          mode: 'External Link',
          type: ['docx', 'doc', 'pdf'],
          render: false,
          newtab: false,
          download: true,
          restricted: false,
        },
      ],
    },
    {
      _id: '5678o9trdsxcvblkn434uykln9',
      name: 'Test Specification',
      slug: 'test-specification',
      decimalClass: '15241',
      doc: [
        {
          format: 'Zipped HTML',
          mode: 'Direct rendering',
          type: ['html', 'zip'],
          render: true,
          newtab: false,
          download: false,
          restricted: false,
        },
        {
          format: 'Word/PDF',
          mode: 'External Link',
          type: ['docx', 'doc', 'pdf'],
          render: false,
          newtab: false,
          download: true,
          restricted: false,
        },
      ],
    },
    {
      _id: '7865edfgnmgw32whlklk09jgf2',
      name: 'User Guide',
      slug: 'user-guide',
      decimalClass: '1553',
      doc: [
        {
          format: 'Zipped HTML',
          mode: 'Direct rendering',
          type: ['html', 'zip'],
          render: true,
          newtab: false,
          download: false,
          restricted: false,
        },
        {
          format: 'Word/PDF',
          mode: 'External Link',
          type: ['docx', 'doc', 'pdf'],
          render: false,
          newtab: false,
          download: true,
          restricted: false,
        },
      ],
    },
    {
      _id: '346yudfgvbnoiuytdf0yugbnk5',
      name: 'Vulnerability Analysis Report',
      slug: 'vulnerability-analysis-report',
      decimalClass: '1597',
      doc: [
        {
          format: 'Markdown',
          mode: 'External Link',
          type: ['md', 'markdown'],
          render: false,
          newtab: true,
          download: false,
          restricted: true,
        },
      ],
    },
  ];
  return primeDDTable;
};
